# apiVersion: v1
# kind: Service
# metadata:
#   name: akhq-service
#   namespace: dev
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#   selector:
#     app: akhq
# apiVersion: v1
# kind: Service
# metadata:
#   name: akhq-service
#   namespace: dev
# spec:
#   selector:
#     app.kubernetes.io/name: akhq
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#       nodePort: 30080
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: akhq-service
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: akhq
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
